### ISSUE TITLE
Offer alternative to Palemoon

### ISSUE THREAD

**Issue by mcarbona1** [kelpup/woof-CE#41]
It might be nice for first time users to use a more modern browser so packaging an alternative might be nice. Alternatively, you could add a package manager so they could choose themselves, although I don't know how difficult that is/if it is in line with the idea of the project. Also, add neofetch?

**Comment by jeanfboueri** [comment]
Hey! Thanks for your suggestion! We already have an issue ( #29 ) where we wanna change the default browser to Firefox or something else since Palemoon isn't a really good browser. There is a package manager in our distro, it's called PPM (Puppy Package Manager), and you can download a bunch of stuff from there (including Firefox).

**Comment by jeanfboueri** [comment]
Leaving issue open for guru point :)

**Comment by bgoodwine** [comment]
guru point added! thanks again :)))
